### ISSUE TITLE
Race condition between texture creation and deletion (via finalizer)

### ISSUE THREAD

**Issue by gravestench** [AllenDang/giu#111]
Texture creation can randomly fail if another texture happens to be finalizing in the background. 

This is causing deadlocks in [our project](http://github.com/OpenDiablo2/Hellspawner).

~~The deadlock is happening between `Texture.release` and `NewTextureFromRgba`.~~ read below

**Comment by gravestench** [comment]
@Essial

**Comment by essial** [comment]
I've been experimenting with mutex locks to ensure that there was absolutely no chance that a free and alloc can happen at the same time, and _still_ got the deadlock. It seems like `CallVal` and `Call` used in Texture.go are extremely unstable and deadlock at odd times.

**Comment by essial** [comment]
I've done more digging, and by swapping to a third party mainthread library in this project, the crashes went away, so there is some kind of error in your mainthread logic it seems.

**Comment by AllenDang** [comment]
@essial I just notice same issue last night and trying to fix it. Can you tell me which third party mainthread lib your are using?

**Comment by essial** [comment]
I used https://github.com/faiface/mainthread which worked great, but did require me to change the texture loading methods to async calls. The only issue was that there seemed to be upwards of half a second until the call was dispatched, but that could have been due to me not being super familiar with the library.

Do you have discord, or could you join our discord? We are _heavily_ using this library (I've already updated our toolset to use your new breaking changes you did a few hours ago), and it'd be nice to collaborate on things we find.

**Comment by AllenDang** [comment]
@essial Sure! I will join your discord once i get my hand  on my laptop.

**Comment by essial** [comment]
OK, well for the time being I think we're going to fork this project and come up with a hot fix as we absolutely have to squash this bug today. We'll do a PR if we get a solution together and will switch back to this one after the merge.

**Comment by essial** [comment]
FYI I've been testing with that PR version all day with 0 crashes.

**Comment by mtp** [comment]
Same problem for me.

**Comment by AllenDang** [comment]
@mtp Can u share a minimal code for testing?

**Comment by mtp** [comment]
> @mtp Can u share a minimal code for testing?

Thank you @AllenDang for your answer.
I had a mix of old and new source file within gui, that was causing the crash. I cleaned up everything, and re-installed your library with the last commit from master.

Now, your TextureFiltering example is crashing and raising a fatal panic with your last commit version.
It comes from the mainthread call in the NewTextureFromRgba function.
I guess you tester your example with the use of mainthread, so I don't understand why it keeps crashing.

**Comment by AllenDang** [comment]
@mtp It's strange. I ran TextureFiltering again without any crash...

**Comment by mtp** [comment]
@AllenDang thank you for your test.
Like I said, I had to call the NewTextureFromRgba from a mainthread.Run, because these NewTextureFromRgba were called before the mainwindow.Run function.
With this fix, I don't know why but I got a "invalid memory address or nil pointer dereference" panic error raised from the NewTextureFromRgba.
I'am still investing the problem.

**Comment by AllenDang** [comment]
@mtp Before MasterWindow.Run, the renderer is not initialized, and to create NewTexture, renderer has to be initialized, that's why you met the error.
Why you have to generate new texture before the master window?

**Comment by mtp** [comment]
@AllenDang I guess that's what you're doing in your TextureFiltering example.
