### ISSUE TITLE
unclear how InputTextMultiline works now

### ISSUE THREAD

**Issue by marcelloh** [AllenDang/giu#115]
This is what I had in previous Giu:
```
g.InputTextMultiline("##text area", &content, -1, -1, g.InputTextFlagsCallbackAlways, nil, onChange),
```
and I know it must be something like this:
```
g.InputTextMultiline("##text area", &content).Size(-1, -1).Callback(g.InputTextFlagsCallbackAlways).OnChange(onChange),
```
but it complains about the Callback part, and I don't know what to do with the nil. I didn't document myself what that nil stands for :-(

**Comment by AllenDang** [comment]
You need to know how to view the definition of a function which could let you know the parameter's type.
Otherwise you will be blocked like this for so many times.

What's code editor you are using? I suggest to use VSCode or Goland which has more necessary support to view definition information for method and type.

Do it like below, note that I'm writing this code from memory, and it's not very accurate, you may need to change the parameter type.
```go
func onCallback(cb imgui.InputTextCallbackData) {
  ...
}

g.InputTextMultiline("##text area", &content).Size(-1, -1).Flags(g.InputTextFlagsCallbackAlways).Callback(onCallback).OnChange(onChange)
```

**Comment by marcelloh** [comment]
ok thanks :-)

An example for people looking for a fix.

Old version:
```
g.InputTextMultiline("##text area", &content, -1, -1, g.InputTextFlagsCallbackAlways, nil, myOnChange),
```
now becomes:
```
g.InputTextMultiline("##text area", &content).Size(-1, -1).Flags(g.InputTextFlagsCallbackAlways).OnChange(myOnChange),
```
