### ISSUE TITLE
unclear (to me) how to do dynamic stuff

### ISSUE THREAD

**Issue by marcelloh** [AllenDang/giu#119]
let's say I have this:
```
func loop() {
    g.SingleWindow("hello world").Layout(g.Layout{
        g.Label("Hello world from giu"),
        g.Line(
            g.Button("Click Me").OnClick(onClickMe),
            g.Button("I'm so cute").OnClick(onImSoCute)),
        })
}
```
But I want the buttons to be  a list of items, it is unclear to me how to do that
Normally I would do something like:
```
func loop() {
    g.SingleWindow("hello world").Layout(g.Layout{
        g.Label("Hello world from giu"),
        g.Line(
           for _,button := range buttons {
              g.Button(button).OnClick(handleClickForButton(button)),
           }
        })
}
```

**Comment by AllenDang** [comment]
You really need to know how to view the parameter type of a function. Otherwise you will met countless questions.

For this case, you should konw the g.Line function accepts []g.Widget as only parameter. And you could assemble the []g.Widget at anywhere and pass it to g.Line to create a line of widgets.

If you understand this, the solution is simple, assemble a slice of widgets, try to pass the slice to g.Line, and you will see the result.

I think your question is not about how to do this specific task, but don't know how to view the function signature.

I admit this lib lacks of lots document, and I'll keep improving it. But I think you should do more learning about golang itself and try to understand giu by reading all the demo code, and before rise any quesiton, search the issue list of this repo, there are lots of common issues are resolved with answer.

You keep opening this kind of issue makes me feel my time is wasted.

**Comment by marcelloh** [comment]
I'm just trying to use what I see. I see an example (https://github.com/AllenDang/giu/wiki) which states:
```
giu.Button("Click Me", nil)
```
I think this is the old solution

So I look at the source:
```
func (b *ButtonWidget) OnClick(onClick func()) *ButtonWidget {
	b.onClick = onClick
	return b
}
```
and I wonder why does the onclick return a buttonwidget pointer?
This is totally not needed. (trying to help you here)
you can get rid of the return, since it's a pointer that you call it with, like &myButton.OnClick()

It's the lack of good documentation that makes me ask the questions, and I am really sorry for that.
and I like to help by making some good examples. But as long as I don't understand why things are the way they are,
it's quite hard for me (and also for others).
Please don't feel like your time is waisted, because it's like you say: making documentation is a waste of time, or helping users is a waste of time, because then you end up only using it yourself, and I think what you have got, might be something really awesome.

**Comment by AllenDang** [comment]
@marcelloh The reason why OnClick returns a button pointer is to support method chain, so user could do code like this.

```go
  // Set size before event handler
  g.Button("Click Me").Size(100).OnClick(...)
  // Set size after event handler
  g.Button("Click Me").OnClick(..).Size(100)
```

Button just has two setter, but other widgets could have several setters, with method chain, user could set any property in any order, which could make code more readable and writable.

At least in my understanding, this helps a lot.

And don't expand my meaning about the document. I know it's necessary to help people to use my lib and I will improve it day by day. I'm just saying this particular issue, how to create batch widgets in a loop, already been asked so many times, if you do a search in the issue list, you will find the answers.

To undestand why `go.Button(item).OnClick(handleClickForButton(item))` doesn't work, you need to know more about golang itself, it has nothing to do with my lib.

**Comment by marcelloh** [comment]
So I puzzled a lot and came to the conclusion for this problem, I should use a rangeBuilder:
```
func layout8() {
	var items []interface{}
	records := libFile.GetAllDirs("/stuff")
	for _, rec := range records {
		items = append(items, rec)
	}
	buttons := g.RangeBuilder("Buttons", items, func(i int, v interface{}) g.Widget {
		str := v.(string)
		return g.Button(str).OnClick(func() {
			fmt.Println(str, "is clicked")
		})
	})

	g.Layout{
		g.Label("--- layout8 ---"),
		buttons,
	}.Build()
}

```
