### ISSUE TITLE
[bug] Applying AlignRight to Button Widget stops OnClick Functionality Working

### ISSUE THREAD

**Issue by bashthekeys** [AllenDang/giu#425]
When creating a ButtonWidget and applying AlignRight to it, visually the button aligns correctly and visually responds to mouse clicks and highlights as expected. However the onClick function is not called. If you then click where the button would be if it had Alignment Left then the onClick function is called.

// This onClick works as expected
g.Button("TEST").OnClick(func() { log.Info("Clicked!") })

//This moves the button etc. but OnClick triggers from the left aligned position
g.Align(g.AlignRight).To(g.Button("TEST").OnClick(func() { log.Info("Clicked!") }))

**Comment by AllenDang** [comment]
@gucio321 Do you have time to take a look?

**Comment by gucio321** [comment]
Sure will work on it net week.

PS merry christmas

**Comment by AllenDang** [comment]
@gucio321 Merry christmas

**Comment by gucio321** [comment]
well, so I got some time to look into this problem.
so, @bashthekeys the temporary solution is (as always) applying alignment manually:
```golang
giu.Custom(func() {
   const myButtonW, myButtonH = 200,30
   availableW, _ := giu.GetAvailableRegion()
   giu.Dummy(availableW-buttonW).Build()
   giu.Button("my awesome button").Size(buttonW, buttonH).Build()
}
```

well your issue is caused by the fact that both buttons (visibla and invisible - the widget that width is measured to apply alignment) have the same imgui id (it is internal giu bug, which I made in the past ;-) )
i don't know at all why it appears :grinning: imo both widgets should be interactable rather then only this last built.
@allendang my idea of solution is to change id of widget inside of `GetWidgetWidth` but it may affect in some other issue when you can interract with this invisible widget anyway. Will open pr in a moment.
