### ISSUE TITLE
[Feature Request]how to make plot line auto change

### ISSUE THREAD

**Issue by lzytaro** [AllenDang/giu#549]
### Your request

hello, i want to make a line plot which can auto change by values. But i found that it would not change when i have didn't move my mouse or doing something

### Additional context

```
			g.TabItem("line").Layout(
				g.Plot("").Plots(
					g.PlotLineXY("xy line", xVal, yVal),
				).AxisLimits(0, 100, 0, 100, g.ConditionAlways),
			),
```
```
var xVal []float64
var yVal []float64

func main() {
	go func() {
		i := 0.0
		for {
			i += 1
			xVal = append(xVal, i)
			yVal = append(yVal, rand.Float64()*100)
			time.Sleep(time.Second)
		}
	}()
	wnd := g.NewMasterWindow("Demo", 800, 600, 0)
	wnd.Run(loop)
}

```
![录制_2022_09_09_14_16_17_905](https://user-images.githubusercontent.com/62502682/189283901-7d437ef8-1a8e-49b5-8437-7911fd40f54f.gif)

**Comment by gucio321** [comment]
Hi ther!
So you mean that if you don't move your mouse, the plot line is not being generated?
This is, because of Power saving stuff - GIU stops rendering, when no user action.
To baypass it, you need to call `giu.Update()` when you want the app to be force-updated.

Some time ago I was writing a simple app for generating sinus line and it'd be a nice example here: https://github.com/gucio321/singen

Let me know if I missunderstood you!

**Comment by lzytaro** [comment]
resolve it
